[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd website && npm install"]

[phases.build]
cmds = ["cd website && npm run build"]

[start]
cmd = "cd website && npm run preview -- --port $PORT --host 0.0.0.0"
